export default {
  atoms: [
    {"attributes": {"label": "Account"}, "id": "purpose-Account", "type": "purpose"},
    {"attributes": {"label": "Admin"}, "id": "purpose-Admin", "type": "purpose"},
    {"attributes": {"label": "AnyContact"}, "id": "purpose-AnyContact", "type": "purpose"},
    {"attributes": {"label": "Arts"}, "id": "purpose-Arts", "type": "purpose"},
    {"attributes": {"label": "AuxPurpose"}, "id": "purpose-AuxPurpose", "type": "purpose"},
    {"attributes": {"label": "Browsing"}, "id": "purpose-Browsing", "type": "purpose"},
    {"attributes": {"label": "Charity"}, "id": "purpose-Charity", "type": "purpose"},
    {"attributes": {"label": "Communicate"}, "id": "purpose-Communicate", "type": "purpose"},
    {"attributes": {"label": "Current"}, "id": "purpose-Current", "type": "purpose"},
    {"attributes": {"label": "Custom"}, "id": "purpose-Custom", "type": "purpose"},
    {"attributes": {"label": "Delivery"}, "id": "purpose-Delivery", "type": "purpose"},
    {"attributes": {"label": "Develop"}, "id": "purpose-Develop", "type": "purpose"},
    {"attributes": {"label": "Downloads"}, "id": "purpose-Downloads", "type": "purpose"},
    {"attributes": {"label": "Education"}, "id": "purpose-Education", "type": "purpose"},
    {"attributes": {"label": "Feedback"}, "id": "purpose-Feedback", "type": "purpose"},
    {"attributes": {"label": "Finmgt"}, "id": "purpose-Finmgt", "type": "purpose"},
    {"attributes": {"label": "Gambling"}, "id": "purpose-Gambling", "type": "purpose"},
    {"attributes": {"label": "Gaming"}, "id": "purpose-Gaming", "type": "purpose"},
    {"attributes": {"label": "Government"}, "id": "purpose-Government", "type": "purpose"},
    {"attributes": {"label": "Health"}, "id": "purpose-Health", "type": "purpose"},
    {"attributes": {"label": "Historical"}, "id": "purpose-Historical", "type": "purpose"},
    {"attributes": {"label": "Login"}, "id": "purpose-Login", "type": "purpose"},
    {"attributes": {"label": "Marketing"}, "id": "purpose-Marketing", "type": "purpose"},
    {"attributes": {"label": "News"}, "id": "purpose-News", "type": "purpose"},
    {"attributes": {"label": "OtherContact"}, "id": "purpose-OtherContact", "type": "purpose"},
    {"attributes": {"label": "Payment"}, "id": "purpose-Payment", "type": "purpose"},
    {"attributes": {"label": "Sales"}, "id": "purpose-Sales", "type": "purpose"},
    {"attributes": {"label": "Search"}, "id": "purpose-Search", "type": "purpose"},
    {"attributes": {"label": "State"}, "id": "purpose-State", "type": "purpose"},
    {"attributes": {"label": "Tailoring"}, "id": "purpose-Tailoring", "type": "purpose"},
    {"attributes": {"label": "Telemarketing"}, "id": "purpose-Telemarketing", "type": "purpose"}
  ]
}